### ISSUE TITLE
Packaged Releases

### ISSUE THREAD

**Issue by dufferzafar** [ibaaj/Regex101.com-offline-app#2]
I think providing packaged [releases](https://github.com/Syskaw/Regex101.com-offline-app/releases) of Regex101 would make sense, as not everyone will have to run the shell script.

Here's a [sample release](https://www.dropbox.com/s/r0gguscne28bf34/Regex101-30-May-2015.zip?dl=0) that I packaged.

**Comment by rcross** [comment]
The slight problem there is that any updates to the code at regex101.com would have to be monitored to stay up to date. Doing it this way allows the code to kept fresh. 

One nice feature though could be cache the files, and have the ability for the command to clear/update the cache.

**Comment by ibaaj** [comment]
I'm not affiliated with regex101.com and I think that if @firasdib (author of regex101) would like to distribute a regex101 package, it would have done it. 

I will update the script in the coming days.

**Comment by ibaaj** [comment]
I added [fonts support](https://github.com/Syskaw/Regex101.com-offline-app/blob/master/runLocalRegex101-full.sh).
