### ISSUE TITLE
Offline script "runLocalRegex101.sh" not working as expected ... 

### ISSUE THREAD

**Issue by fekigor** [ibaaj/Regex101.com-offline-app#5]
Hi!

Your script now, not working as expected because some *.js files on www.regex101.com are not accessible any more. I think now is "switched ON" force redirect to index.html on regexp101.com and wget can't download source files any more.

SOLUTION:
I make archive with your script runLocalRegex101.sh (modified) and with offline files from www.regexp101.com (from this [source](https://www.dropbox.com/s/r0gguscne28bf34/Regex101-30-May-2015.zip?dl=0)). 
File ./js/mist/matcher.js was also edited, replaced wrong files names:
/js/javascript.regexp101.js - > /js/javascript.js 
/js/pcre.regexp101.js - > /js/pcre.js

My archive possible to download by this [link].(https://www.upload.ee/files/6220550/Regex101.tar.gz.html)

my version of "runLocalRegex101.sh" (wget is not needed any more, we use local copy from folder Regex101):

`#!/bin/bash

trap ctrl_c SIGINT;

pwd=`pwd`
tempdir="${pwd}/Regex101"
echo "TempDIR=${tempdir}"

pushd $tempdir

function server {
  python -m SimpleHTTPServer $@;
}

function cleanup {
 echo "Stop the server ... ";
 popd;
}

function ctrl_c {
 cleanup;
 exit $?;
}

server $@;`

**Comment by ibaaj** [comment]
Hello, thanks for submitting this issue.
Regex101 changed a little bit yes
Now they do not use `./js/javascript.regex101.js`, `./js/pcre.regex101.js`, and `./js/pcrelib16.js`, but use `./pcrelib.js` and `./pcreWorker.js`. 

I will update the script now

**Comment by ibaaj** [comment]
its working now 😀
