### ISSUE TITLE
Issue with FontAwesome

### ISSUE THREAD

**Issue by joshewilliams** [ibaaj/Regex101.com-offline-app#6]
It appears that the location where FontAwesome used to host FontAwesome 4.4.0 is no longer available. This can be fixed by using the following link instead:

http://fontawesome.io/assets/font-awesome-4.7.0.zip 

I didn't even bother changing the name that this zip is saved as, since that file is deleted shortly afterward.

**Comment by ibaaj** [comment]
Hello,

Thanks for contributing!

I checked and noticed that Regex101 doesn't rely on FontAwesome package so far.

I simply deleted the ["full" script](https://github.com/ibaaj/Regex101.com-offline-app/commit/5ebfd65afa5a44081f222a66059ca07fb18907ce).

Thanks for your help!
