### ISSUE TITLE
Made an updated script to use the latest regex101 offline.

### ISSUE THREAD

**Issue by chillyshackk** [ibaaj/Regex101.com-offline-app#7]
Not really an issue, just made an updated version as this one no longer works, there might be some useless file downloaded in my list I haven't fully checked but that is how I got it working, thought I would share, feel free to remove/fix anything if needed:

#!/bin/bash

trap ctrl_c SIGINT;

#put the download and run scripts in that same folder:
pushd /path/where/you/want/regex101;

wget -r --no-host-directories --no-parent https://regex101.com;
wget -r --no-host-directories --no-parent https://regex101.com/static/translations/english.json;
wget --output-document ./static/pcreWorker.js https://regex101.com/static/pcreWorker.js;
wget --output-document ./static/pcrelib.js https://regex101.com/static/pcrelib.js;
wget --output-document ./javascriptWorker.js http://regex101.com/javascriptWorker.js;
wget --output-document ./static/sw.js http://regex101.com/static/sw.js;
wget --output-document ./static/javascriptWorker.js http://regex101.com/static/javascriptWorker.js;
wget --output-document ./static/vendor.71600b0e.chunk.js http://regex101.com/static/vendor.71600b0e.chunk.js;
wget --output-document ./static/golangWorker.js http://regex101.com/static/golangWorker.js;
wget --output-document ./static/english.json http://regex101.com/static/translations/english.json;
wget --output-document ./static/golang.js http://regex101.com/static/golang.js;
wget --output-document ./static/bundle.f566b334954e3b444def.css https://regex101.com/static/bundle.f566b334954e3b444def.css;
wget --output-document ./static/bundle.f566b334954e3b444def.css.map https://regex101.com/static/bundle.f566b334954e3b444def.css.map;

function server {
python -m SimpleHTTPServer $@;
}

function cleanup {
echo "Closing...";
popd;
}

function ctrl_c {
cleanup;
exit $?;
}

server $@;

**Comment by chillyshackk** [comment]
[download_run_regex101.sh.txt](https://github.com/ibaaj/Regex101.com-offline-app/files/3205976/download_run_regex101.sh.txt)
[run_regex101.sh.txt](https://github.com/ibaaj/Regex101.com-offline-app/files/3205977/run_regex101.sh.txt)

**Comment by p1r4t3-s4il0r** [comment]
Any new update ? This script does seems to be working anymore

Thks
